name: challenge
description: A new Flutter project.


publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #UX/UI
  google_fonts: ^2.3.3
  flutter_svg: ^1.1.0
  another_flushbar: ^1.10.29
  flutter_native_splash: ^2.2.3
  mask_text_input_formatter: ^2.3.0
  pattern_formatter: ^2.0.0
  intl: ^0.17.0
  timezone: ^0.8.0

  #State Management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3

  #Usefull tools
  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2
  progress_indicators: ^1.0.0

  #http - dio
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0

  #Firebase
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11
  

  
  flutter_lints: ^2.0.0





flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/


flutter_native_splash:
  color: "#BE2BFA"
  android_12:
    icon_background_color: "BE2BFA"